spring:
  application:
    name: config
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:loc}
    group:
      "loc": "loc"
      "dev": "dev"
      "real": "real"
  config:
    import: "optional:configserver:http://localhost:8088"
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    thymeleaf:
      prefix:
        classpath: templates/
      check-template-location: true
      sufix: .html
      mode: HTML5
      cache: false

management:
  endpoints:
    web:
      exposure:
        include: refresh

mybatis: # type을 쉽게 쓰기 위해서 dto 패키지를 type-aliaes에 설정
  type-aliases-package: com.study.springconfigclient.domain
  mapper-locations: /mappers/*.xml
